combine_control_expr = false
wrap_comments = true
comment_width = 60
enum_discrim_align_threshold = 20
fn_single_line = true
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
reorder_modules = false
struct_field_align_threshold = 20
trailing_semicolon = true
use_field_init_shorthand = true
use_try_shorthand = true